spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/random-workout-routine
    username: random-workout-routine
    password: random-workout-routine
    initialization-mode: always
  jpa.hibernate.ddl-auto: update
---
spring:
  profiles: prod
  datasource.url: jdbc:postgresql://db:5432/random-workout-routine
---
spring:
  profiles: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:random-workout-routine
  jpa.hibernate.ddl-auto: create-drop
