spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/random-workout-routine
    username: random-workout-routine
    password: random-workout-routine
    initialization-mode: always
  jpa.hibernate.ddl-auto: update
---
server.servlet.context-path: /rwr
spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://db:5432/random-workout-routine
    password: j5NEo9*xrG&*
