name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_jar:
    name: Build JAR
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v1
      with:
        name: jar
        path: web/build/libs
  build_image:
    name: Build Docker Image
    needs: [build_jar]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download JAR artifact
      uses: actions/download-artifact@v1
      with:
        name: jar
    - name: Set image tag variable
      run: echo "IMAGE_TAG=rwr:$(date +%s)" >> $GITHUB_ENV
    - name: Build the image
      run: docker build . --file Dockerfile --tag $IMAGE_TAG
    - name: Save the image
      run: docker save $IMAGE_TAG > rwr.tar
    - name: Upload image artifact
      uses: actions/upload-artifact@v1
      with:
        name: image
        path: rwr.tar
