# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_jar:
    name: Build JAR
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v1
      with:
        name: jar
        path: build/libs
  build_image:
    name: Build Docker Image
    needs: [build_jar]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download JAR artifact
      uses: actions/download-artifact@v1
      with:
        name: jar
    - name: Build the image
      run: docker build . --file Dockerfile --tag rwr:$(date +%s)
